---
name: OMNIDOME
locales: [en]
subdomain: loco-omnidome
domains: [omnido.me, www.omnido.me, loco-omnidome.metalogiciel.com, loco-omnidome.meristeda.com]
seo_title: OMNIDOME / FULLDOME MAPPING SOFTWARE
meta_keywords: Omnidome, Full dome mapping software, VJ software, dome mapping, planetariums,
  Berlin, Lichtpiraten, Video mapping
meta_description: some meta description
timezone: Berlin
